(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["pages/land/components/tp_layout"],{"6ae4":function(t,e,r){"use strict";function n(t,e){var r=Object.keys(t);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(t);e&&(n=n.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),r.push.apply(r,n)}return r}function u(t){for(var e=1;e<arguments.length;e++){var r=null!=arguments[e]?arguments[e]:{};e%2?n(Object(r),!0).forEach((function(e){o(t,e,r[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(r)):n(Object(r)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(r,e))}))}return t}function o(t,e,r){return e in t?Object.defineProperty(t,e,{value:r,enumerable:!0,configurable:!0,writable:!0}):t[e]=r,t}Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var c={name:"TpLayout",props:{tpl:{type:[String,Number],default:1},entry:{type:Object,default:function(){}},blockWidth:{type:[Number,String],default:100},blockHeight:{type:[Number,String],default:100},imgMode:{type:String,default:"widthFix"},customImgStyle:{type:[Boolean,Object],default:!1}},data:function(){return{}},mounted:function(){},computed:{imgStyle:function(){var t={};if(this.customImgStyle&&"object"===typeof this.customImgStyle){var e=this.customImgStyle,r=e.width,n=e.height;r&&(t.width=r),n&&(t.height=n)}return u(u({},this.customImgStyle),t)}},methods:{}};e.default=c},"70f4":function(t,e,r){"use strict";r.r(e);var n=r("7d44"),u=r("f767");for(var o in u)"default"!==o&&function(t){r.d(e,t,(function(){return u[t]}))}(o);r("b938");var c,i=r("f0c5"),a=Object(i["a"])(u["default"],n["b"],n["c"],!1,null,"2c5a9fdd",null,!1,n["a"],c);e["default"]=a.exports},"7d44":function(t,e,r){"use strict";var n;r.d(e,"b",(function(){return u})),r.d(e,"c",(function(){return o})),r.d(e,"a",(function(){return n}));var u=function(){var t=this,e=t.$createElement,r=(t._self._c,t.entry.url?t.__get_style([t.imgStyle]):null);t.$mp.data=Object.assign({},{$root:{s0:r}})},o=[]},f767:function(t,e,r){"use strict";r.r(e);var n=r("6ae4"),u=r.n(n);for(var o in n)"default"!==o&&function(t){r.d(e,t,(function(){return n[t]}))}(o);e["default"]=u.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'pages/land/components/tp_layout-create-component',
    {
        'pages/land/components/tp_layout-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("70f4"))
        })
    },
    [['pages/land/components/tp_layout-create-component']]
]);
