(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/tm-icon/index"],{"1c2d":function(t,e,n){"use strict";n.r(e);var r=n("a40f"),o=n.n(r);for(var i in r)"default"!==i&&function(t){n.d(e,t,(function(){return r[t]}))}(i);e["default"]=o.a},"663d":function(t,e,n){"use strict";var r;n.d(e,"b",(function(){return o})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return r}));var o=function(){var t=this,e=t.$createElement,n=(t._self._c,t.svg&&t.url?t.__get_style([t.svgExternalStyle]):null),r=t.svg?null:t.__get_style([t.iconStyle]);t.$mp.data=Object.assign({},{$root:{s0:n,s1:r}})},i=[]},a40f:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=i(n("2010")),o=n("8e92");function i(t){return t&&t.__esModule?t:{default:t}}var a={name:"TmIcon",props:{type:{type:String,required:!0},color:String,className:String,width:[Number,String],height:[Number,String],size:{type:[Number,String],default:28},svg:{type:Boolean,default:!1},rotate:{type:[Number,String],default:0}},data:function(){return{prefixCls:"".concat(r.default.prefix,"-icon")}},computed:{url:function(){return(0,o.isUrl)(this.type)},svgExternalStyle:function(){return{mask:"url(".concat(this.type,") no-repeat 50% 50%"),"-webkit-mask":"url(".concat(this.type,") no-repeat 50% 50%")}},iconName:function(){return"#".concat(r.default.prefix,"-").concat(this.type)},iconStyle:function(){var t={};return this.color&&(t.color=this.color),this.size&&(t.fontSize="".concat(this.size,"rpx")),this.rotate&&(t.transform="rotate(".concat(this.rotate,"deg)")),t}},methods:{onClick:function(){this.$emit("click")}}};e.default=a},ddea:function(t,e,n){"use strict";n.r(e);var r=n("663d"),o=n("1c2d");for(var i in o)"default"!==i&&function(t){n.d(e,t,(function(){return o[t]}))}(i);n("a3ed");var a,c=n("f0c5"),u=Object(c["a"])(o["default"],r["b"],r["c"],!1,null,"4b41eb3c",null,!1,r["a"],a);e["default"]=u.exports}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/tm-icon/index-create-component',
    {
        'components/tm-icon/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("ddea"))
        })
    },
    [['components/tm-icon/index-create-component']]
]);
