(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/tm-avatar/index"],{"01fd":function(t,e,n){"use strict";n.r(e);var r=n("b876"),a=n.n(r);for(var i in r)"default"!==i&&function(t){n.d(e,t,(function(){return r[t]}))}(i);e["default"]=a.a},2287:function(t,e,n){"use strict";n.d(e,"b",(function(){return a})),n.d(e,"c",(function(){return i})),n.d(e,"a",(function(){return r}));var r={tmIcon:function(){return Promise.all([n.e("common/vendor"),n.e("components/tm-icon/index")]).then(n.bind(null,"ddea"))}},a=function(){var t=this,e=t.$createElement,n=(t._self._c,Object.keys(t.$slots)),r=t.image||t.icon||n.length?t.__get_style([t.avatarStyle]):null;t.$mp.data=Object.assign({},{$root:{g0:n,s0:r}})},i=[]},"67ae":function(t,e,n){"use strict";n.r(e);var r=n("2287"),a=n("01fd");for(var i in a)"default"!==i&&function(t){n.d(e,t,(function(){return a[t]}))}(i);n("ec51");var o,c=n("f0c5"),u=Object(c["a"])(a["default"],r["b"],r["c"],!1,null,"2e8a7672",null,!1,r["a"],o);e["default"]=u.exports},b876:function(t,e,n){"use strict";Object.defineProperty(e,"__esModule",{value:!0}),e.default=void 0;var r=a(n("2010"));function a(t){return t&&t.__esModule?t:{default:t}}function i(t,e){var n=Object.keys(t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(t);e&&(r=r.filter((function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),n.push.apply(n,r)}return n}function o(t){for(var e=1;e<arguments.length;e++){var n=null!=arguments[e]?arguments[e]:{};e%2?i(Object(n),!0).forEach((function(e){c(t,e,n[e])})):Object.getOwnPropertyDescriptors?Object.defineProperties(t,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(e){Object.defineProperty(t,e,Object.getOwnPropertyDescriptor(n,e))}))}return t}function c(t,e,n){return e in t?Object.defineProperty(t,e,{value:n,enumerable:!0,configurable:!0,writable:!0}):t[e]=n,t}var u={name:"TmAvatar",props:{shape:{validator:function(t){return["circle","square"].includes(t)},default:"circle"},size:{type:[String,Number],default:"default"},shadow:{type:Boolean,default:!1},image:String,icon:String,iconColor:String,iconSize:{type:[Number,String],default:28},avatarBg:String,mode:{type:String,default:"aspectFill"},customStyle:{type:Object,default:function(){}}},data:function(){return{prefixCls:"".concat(r.default.prefix,"-avatar")}},computed:{avatarStyle:function(){var t={};return this.avatarBg&&(this.avatarBg.includes("gradient")?t.backgroundImage=this.avatarBg:t.backgroundColor=this.avatarBg),this.size&&Number(this.size)&&(t.width="".concat(this.size,"rpx"),t.height="".concat(this.size,"rpx")),o(o({},t),this.customStyle)}},methods:{handleBoxClick:function(t){this.$emit("onClick",t)},handleImgError:function(t){this.$emit("onError",t)}}};e.default=u}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/tm-avatar/index-create-component',
    {
        'components/tm-avatar/index-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('543d')['createComponent'](__webpack_require__("67ae"))
        })
    },
    [['components/tm-avatar/index-create-component']]
]);
